### PR TITLE
Storage get count

### PR DESCRIPTION
**Pull request by Lenny7120**
Compare and merge it

### CODE REVIEW

**Comment by Lenny7120** [comment]
Merge it

**Comment by Lenny7120** [comment]
@ Akua-95 merge the branches

**Comment by Lenny7120** [comment]
@Lenny7120 merge it

**Comment by Lenny7120** [comment]
@Akua-95 merge it

**Comment by Akua-95** [comment]
Merging Restful API

**Comment by Akua-95** [comment]
updated storage get count

**Comment by Akua-95** [comment]
Merge storage get count

**Comment by Akua-95** [comment]
Merge storage get count

**Comment by Akua-95** [comment]
Merge it

**Review by Lenny7120 — COMMENTED** [review]
Merge branches

**Comment by Akua-95** [comment]
Merge

**Comment by Akua-95** [comment]
Merge storage get count

**Comment by Akua-95** [comment]
Merge storage get count

**Pull request closed without merging**
