### PR TITLE
improving models 

### PR DESCRIPTION
**Pull request by dennisnderitu254**
db_storage and file_storage - adding get and count methods alongside their tests

### CODE REVIEW

**Comment by dennisnderitu254** [comment]
db_storage and file_storage - adding get and count methods alongside their tests

**Comment by dennisnderitu254** [comment]
@NjeriMaina4172

**Comment by dennisnderitu254** [comment]
@NjeriMaina4172
This is a pull request that needs a review

**Comment by NjeriMaina4172** [comment]
Improved storage

Adding a method to retrieve one object - get method

Adding a method to count the number of objects in storage - count method.

**Pull request closed without merging**
