### PR TITLE
merge master ans storage get count 

### PR DESCRIPTION
**Pull request by Slimanyy**

### CODE REVIEW

**Comment by Johndoeslimany** [comment]
NO ISSUES REPO CAN BE MERGED SUCCESSFULLY

**Review by Johndoeslimany — APPROVED** [review]

**Review by Johndoeslimany — APPROVED** [review]

**Review by Slimanyy — COMMENTED** [review]
Changed storage

**Review by Johndoeslimany — APPROVED** [review]

**Comment by Nnenna-udefi** [comment]
Merge master with new branch

**Review by Pizzosta — COMMENTED** [review]
works well

**Pull request closed without merging**
