### PR TITLE
Add more unittests

### PR DESCRIPTION
**Pull request by Bsakwa**

### CODE REVIEW

**Comment by Bsakwa** [comment]
@Emma0147 Hello, Please review my merge request. Thank you

**Review by Bsakwa — COMMENTED** [review]
Added tests to validate count and get methods

**Comment by Bsakwa** [comment]
Hi @Victor-Amonde and  @OtaraAlex Whoever gets it first. Please review and merge changes. Thanks

**Comment by OtaraAlex** [comment]
Hi Brian, I don't have the write access to merge the PR

**Comment by Bsakwa** [comment]
@OtaraAlex Could you approve the changes? I can do the merge once done.

**Review by OtaraAlex — APPROVED** [review]

**Review by OtaraAlex — APPROVED** [review]

**Review by Emma0147 — COMMENTED** [review]
Nice Job

**Pull request closed without merging**
