### PR TITLE
Storage get count

### PR DESCRIPTION
**Pull request by davykoch**
On this branch we did improvements on storage

### CODE REVIEW

**Comment by samiunique** [comment]
no conflict

**Comment by Annsrutto** [comment]
Reviewed

**Comment by davykoch** [comment]
okay

**Comment by davykoch** [comment]
okay

**Review by MegaChie — APPROVED** [review]
all files are bins, hope i do not mess it up for you

**Review by Annsrutto — COMMENTED** [review]
No conflicts

**Comment by davykoch** [comment]
> all files are bins, hope i do not mess it up for you

meaning?

**Comment by MegaChie** [comment]
> > all files are bins, hope i do not mess it up for you
> 
> meaning?

you need to delete them. for the sake of clarity and order

**Pull request closed without merging**
