### PR TITLE
Storage get count

### PR DESCRIPTION
**Pull request by JoyNgaru**
Update DBStorage and FileStorage with new objects

### CODE REVIEW

**Comment by count58** [comment]
Great job done

**Review by count58 — APPROVED** [review]

**Review by count58 — APPROVED** [review]
good job

**Review by Joram21 — APPROVED** [review]

**Review by Joram21 — APPROVED** [review]

**Comment by Joram21** [comment]
nice

**Review by Joram21 — APPROVED** [review]

**Comment by JoyNgaru** [comment]
thanx for the review

**Comment by JoyNgaru** [comment]
Thank you for the review,,,

**Comment by JoyNgaru** [comment]
f

**Pull request closed without merging**
