### PR TITLE
Update db_storage and filestorage

### PR DESCRIPTION
**Pull request by Esther-Wagatwe**
Updated filestorage and db_storage by adding get and count methods.

### CODE REVIEW

**Comment by Esther-Wagatwe** [comment]
Pull request made

**Review by EstherWagatwe — APPROVED** [review]
Approved

**Review by EstherWagatwe — CHANGES_REQUESTED** [review]
Pull request approved

**Review by EstherWagatwe — APPROVED** [review]
Approve

**Review by MbongeniChristian3 — APPROVED** [review]

**Review by ngari-kev — APPROVED** [review]
Works well.

**Comment by MbongeniChristian3** [comment]
Hi

**Comment by MbongeniChristian3** [comment]
Did you manage to merge the pull request??

**Pull request closed without merging**
