### PR TITLE
storage changes

### PR DESCRIPTION
**Pull request by ericmasila**
we've updated the FileStorage and DBStorage

### CODE REVIEW

**Comment by Victorxxiv** [comment]
Everything seems available up to this step.

**Comment by GaboJohn** [comment]
Looks just fine

**Comment by Victorxxiv** [comment]
Sure

**Review by ericmasila — COMMENTED** [review]
changes reviewed

**Comment by Victorxxiv** [comment]
Still, I'm not able to review, or see any review button.

**Review by Victorxxiv — APPROVED** [review]

**Pull request closed without merging**
