### PR TITLE
update code

### PR DESCRIPTION
**Pull request by raxidbou4nja**

### CODE REVIEW

**Comment by Jonahjohnzon** [comment]
storage_count update

**Comment by NourhanAli10** [comment]
update

**Comment by janenyasoro** [comment]
Storage count update

**Comment by Anana99** [comment]
API and model

**Comment by ahmed2103** [comment]
l

**Comment by Nekgate** [comment]
updated storage count

**Comment by ayoubleass** [comment]
Adding two new methods to both DBStorage and FileStorage

**Comment by Miss-Siba** [comment]
storage count update

**Comment by Keithclinton** [comment]
Storage update

**Comment by Trisha256** [comment]
storage_base_count

**Comment by Omarfathi22** [comment]
0x05. AirBnB clone - RESTful API

**Comment by Stringpappy** [comment]
creating a pull request for RESTful api task 2

**Pull request closed without merging**
